// <auto-generated />
using System;
using FamilyTree.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyTree.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240609120208_UserTable")]
    partial class UserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FamilyTree.Models.Master.ParentChildMapping", b =>
                {
                    b.Property<int>("ParentChildMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ParentChildMappingId"));

                    b.Property<int?>("Person1Id")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Person2Id")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("RelationTypeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("ParentChildMappingId");

                    b.ToTable("ParentChildMapping");
                });

            modelBuilder.Entity("FamilyTree.Models.Master.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CreationDatetime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateOfDeath")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char(2)");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char(2)");

                    b.HasKey("PersonId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("FamilyTree.Models.Master.RelationMapping", b =>
                {
                    b.Property<int>("RelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RelationId"));

                    b.Property<DateTime?>("CreationDatetime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("LastUpdatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Person1Id")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Person2Id")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<int?>("RelationTypeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("RelationId");

                    b.ToTable("RelationMapping");
                });

            modelBuilder.Entity("FamilyTree.Models.Master.RelationType", b =>
                {
                    b.Property<int>("RelationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RelationTypeId"));

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("DATETIME");

                    b.Property<int>("LastUpdatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDatetime")
                        .HasColumnType("DATETIME");

                    b.Property<string>("RelationTypeCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(2)");

                    b.Property<string>("RelationTypeDescription")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(150)");

                    b.HasKey("RelationTypeId");

                    b.ToTable("RelationType");
                });

            modelBuilder.Entity("FamilyTree.Models.Master.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreationDatetime")
                        .HasColumnType("DATETIME");

                    b.Property<int>("LastUpdatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("FamilyTree.Models.Master.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<DateTime?>("CreationDatetime")
                        .HasColumnType("DATETIME");

                    b.Property<string>("IsSuperUserRole")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<int>("LastUpdatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("DATETIME");

                    b.Property<string>("RoleActivityIds")
                        .IsRequired()
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("UserRoleDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("UserRoleId");

                    b.ToTable("UserRole");
                });
#pragma warning restore 612, 618
        }
    }
}
